NUMPY

In [1]:
import numpy as np

In [ ]:
np.__version__  #to see any versions type__shift and enter

'2.1.3'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
#converting list in to array

arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

#interview question
#diff b/w list and array

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10,20,5)#(start,stop,step)

array([10, 15])

In [11]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.arange(20,10)#2nd arg should be greater than 1st arg

array([], dtype=int64)

In [15]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [ ]:
#np.zeros

np.zeros(5) #parameter tuning ====means system generated 

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5, dtype=int) #hyperparameter tuning ====user generated(requirment)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(5)#1darray

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros([2,2])#2darray

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros([5,4])#ndarray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
'''np.zeros([2,4]) here bydefault left number is row=2 and right one is column=4'''

In [21]:
np.zeros([10,10], dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ONES

In [22]:
#ones
np.ones(2)

array([1., 1.])

In [24]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [25]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.ones([10,10], dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

RANDOM

In [29]:
#random is used to generate random numbers.====eg.OTP
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
#rand is a function comes from module==random

np.random.rand(2,4)#for each run values will change

array([[0.61135783, 0.66656296, 0.63300659, 0.94873499],
       [0.36778166, 0.91922117, 0.31457533, 0.07186547]])

In [ ]:
np.random.rand(3)# below we get diff o/p at every run

array([0.47714854, 0.22288421, 0.65262993])

In [34]:
np.random.randint(3,4)

3

In [37]:
np.random.randint(0,10)

3

In [38]:
np.random.randint(0,10)

2

In [42]:
np.random.randint(0,10)

7

In [45]:
np.random.randint(0,10)

6

In [ ]:
np.random.randint(0,10,4)#==it gives 4 elements b/w 0-10

array([8, 4, 4, 8], dtype=int32)

In [47]:
np.random.randint(0,10,4)

array([9, 3, 2, 9], dtype=int32)

In [48]:
np.random.randint(0,10,4)

array([6, 4, 6, 9], dtype=int32)

In [49]:
np.random.randint(0,10,4)

array([5, 6, 0, 6], dtype=int32)

In [ ]:
np.random.randint(10,40,(4,8))

array([[30, 32, 23, 31, 15, 30, 15, 20],
       [39, 38, 18, 24, 39, 20, 17, 21],
       [21, 20, 10, 28, 26, 25, 18, 24],
       [29, 18, 28, 10, 25, 15, 24, 19]], dtype=int32)

above and below we are getting int 32 ...so to avoid it every time time we should create variable and use print to print it.

In [51]:
n = np.random.randint(10,40,(4,8))

In [52]:
n

array([[28, 32, 19, 34, 27, 19, 27, 27],
       [22, 19, 31, 35, 24, 28, 13, 15],
       [17, 34, 27, 13, 25, 37, 23, 26],
       [30, 29, 29, 39, 37, 39, 17, 29]], dtype=int32)

INDEX AND SLICING IN MATRIX

In [ ]:
n[0]#row

array([28, 32, 19, 34, 27, 19, 27, 27], dtype=int32)

In [54]:
n[3]

array([30, 29, 29, 39, 37, 39, 17, 29], dtype=int32)

In [55]:
n[0:4]

array([[28, 32, 19, 34, 27, 19, 27, 27],
       [22, 19, 31, 35, 24, 28, 13, 15],
       [17, 34, 27, 13, 25, 37, 23, 26],
       [30, 29, 29, 39, 37, 39, 17, 29]], dtype=int32)

In [56]:
n[0:3]

array([[28, 32, 19, 34, 27, 19, 27, 27],
       [22, 19, 31, 35, 24, 28, 13, 15],
       [17, 34, 27, 13, 25, 37, 23, 26]], dtype=int32)

In [ ]:
n[::-1]#reverse the matrix

array([[30, 29, 29, 39, 37, 39, 17, 29],
       [17, 34, 27, 13, 25, 37, 23, 26],
       [22, 19, 31, 35, 24, 28, 13, 15],
       [28, 32, 19, 34, 27, 19, 27, 27]], dtype=int32)

In [ ]:
n = np.random.randint(10,40,(8,8))

In [59]:
n

array([[10, 31, 37, 26, 20, 16, 36, 22],
       [21, 14, 24, 10, 12, 32, 36, 30],
       [17, 30, 36, 38, 11, 26, 24, 30],
       [13, 32, 35, 31, 16, 39, 26, 16],
       [14, 12, 21, 29, 34, 11, 31, 30],
       [30, 29, 16, 19, 31, 17, 28, 32],
       [36, 10, 32, 38, 11, 24, 16, 35],
       [17, 23, 25, 18, 30, 21, 33, 20]], dtype=int32)

In [ ]:
n[::2]# it skips 2nd line at evey print.....so it prints 0,2,4,6

array([[10, 31, 37, 26, 20, 16, 36, 22],
       [17, 30, 36, 38, 11, 26, 24, 30],
       [14, 12, 21, 29, 34, 11, 31, 30],
       [36, 10, 32, 38, 11, 24, 16, 35]], dtype=int32)

In [63]:
n

array([[10, 31, 37, 26, 20, 16, 36, 22],
       [21, 14, 24, 10, 12, 32, 36, 30],
       [17, 30, 36, 38, 11, 26, 24, 30],
       [13, 32, 35, 31, 16, 39, 26, 16],
       [14, 12, 21, 29, 34, 11, 31, 30],
       [30, 29, 16, 19, 31, 17, 28, 32],
       [36, 10, 32, 38, 11, 24, 16, 35],
       [17, 23, 25, 18, 30, 21, 33, 20]], dtype=int32)

COMMA (,) IN MATRIX

In [ ]:
n[0,4]#it prints number at 0index row and 4 index column

np.int32(20)

In [62]:
n[5,-3]

np.int32(17)

In [64]:
n[2,5]

np.int32(26)

In [65]:
n[-3,7]

np.int32(32)

: IN MATRIX ====PRINTS RECORDS
, IN MATRIX ====PRINTS SPECIFIC POSITIONS

RESHAPE

In [ ]:
np.arange(1,13).reshape(3,4)#it matches numbers

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(3,2)# as there are 12 elements it will work with multiples like 2,6..6,2..3,4..4,2..etc

ValueError: cannot reshape array of size 12 into shape (3,2)

In [69]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [70]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])